language: python

git:
  depth: 10

notifications:
  email: false

services:
  - docker

before_script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)

jobs:
  include:
  - python: 3.9
    install: pip install --upgrade pip && pip install pandas==1.2.5 numpy==1.20.2 matplotlib==3.3.4 requests==2.25.1 pathlib==1.0.1
    script: cd testing && make test_all
